stages:
    - build
    - test

default:
    tags: [dev]

build:
    stage: build
    artifacts:
        paths:
            - var
            - vendor
    script:
        - composer install

unit-test:
    stage: test
    dependencies:
        - build
    script:
        - make cs-cicd
        - make analyse-cicd
        - make coverage-cicd
    coverage: /^\s*Lines:\s*\d+.\d+\%/
