stages:
    - build
    - test

default:
    tags: [dev]

build:
    stage: build
    artifacts:
        paths:
            - vendor/
    script:
        - composer install --classmap-authoritative

unit-test:
    stage: test
    dependencies:
        - build
    script:
        - whoami
        - ./vendor/bin/phpstan analyse
        - shopt -s expand_aliases
        - alias -p
        - php_coverage ./vendor/bin/phpunit --coverage-text --colors=never
        - ./vendor/bin/php-cs-fixer fix --dry-run
    coverage: /^\s*Lines:\s*\d+.\d+\%/
