name: CI
on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Compile > Validate composer
              run: composer validate --strict

            - name: Compile > Cache composer
              uses: actions/cache@v3
              with:
                  path: vendor
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: Compile > Install composer
              run: composer install

            - name: Lint > Coding standards
              run: vendor/bin/php-cs-fixer fix --dry-run --stop-on-violation

            - name: Analyze > Static code analysis
              run: vendor/bin/phpstan analyse

            - name: Test > Unit tests
              uses: php-actions/phpunit@v3
              env:
                  XDEBUG_MODE: coverage
              with:
                  php_extensions: "xdebug"
                  coverage_clover: ".coverage_clover.xml"

            - name: Test > Generate code coverage
              env:
                  XDEBUG_MODE: coverage
              run: vendor/bin/phpunit --do-not-cache-result --coverage-clover=.coverage_clover.xml --display-warnings

            - name: Artifact > Codacy coverage report
              uses: codacy/codacy-coverage-reporter-action@v1.3
              with:
                  project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                  coverage-reports: ".coverage_clover.xml"
